[package]
name = "reactor-3d"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = { version = "0.31", features = ["serde", "persistence", "wgpu"] }
egui = "0.31"
egui-probe = { git = "https://github.com/zakarumych/egui-probe.git", features = ["derive"] }
egui-scale = "0.1"
egui_dock = { version = "0.16", features = ["serde"] }
egui_extras = { version = "0.31", features = ["all_loaders"] }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1" }
